spring:
  datasource:
    name: blog
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: linhui
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    poolPreparedStatements: true
  thymeleaf:
    mode: LEGACYHTML5
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.linh.model






